---
collections:
  - name: kubernetes.core
  - name: infra.aap_utilities
  - name: infra.controller_configuration
  - name: git+https://github.com/redhat-cop/openshift_virtualization_migration.git
    version: main